- name: disable default nodejs
ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs 20
ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs # can use dnf also
ansible.builtin.package: 
name: nodejs
state: present

- name: create expense user
ansible.builtin.user:
name: expense

- name: create app directory
ansible.builtin.file:
path: /app
state: directory

- name: download the backend code
ansible.builtin.get_url: 
url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
dest: /tmp/backend.zip

- name: extract the code
ansible.builtin.unarchive:
src: /tmp/backend.zip
dest: /app

- name: copy backend service
ansible.builtin.copy: 
src: backend.service #from the service file
dest: /etc/systemd/system/backend.service 

- name: import